{
  inputs,
  cell,
}: let
  inherit (inputs.nixpkgs) lib;
  pkgs = import inputs.nixpkgs {
    inherit (inputs.nixpkgs) system;
    overlays = [
      inputs.gomod2nix.overlays.default
    ];
  };
in {
  # Main application package
  default = pkgs.buildGoApplication {
    pname = "mtg-treacherest";
    version = "0.1.0";

    src = inputs.self + /nix/app;

    # Go module dependencies (will be generated by gomod2nix)
    modules = inputs.self + /nix/app/gomod2nix.toml;

    # Set the main package path
    subPackages = ["cmd/server"];

    # Build flags
    ldflags = [
      "-s"
      "-w" # Strip debug info
    ];

    meta = with lib; {
      description = "MTG Treachery game implementation with Datastar";
      license = licenses.mit;
      platforms = platforms.linux ++ platforms.darwin;
    };
  };

  # Development version (for faster builds during development)
  dev = pkgs.buildGoApplication {
    pname = "mtg-treacherest-dev";
    version = "dev";

    src = inputs.self + /nix/app;
    modules = inputs.self + /nix/app/gomod2nix.toml;
    subPackages = ["cmd/server"];

    # Development build flags (keep debug info)
    ldflags = [];

    meta = with lib; {
      description = "MTG Treacherest game implementation (development build)";
    };
  };
}
