# Base configuration - shared defaults for all environments
server:
  maxPlayersPerRoom: 20
  minPlayersPerRoom: 1
  defaultGameSize: 5
  roomCodeLength: 5
  roomTimeout: 24h
  
  # Timeouts
  readTimeout: 15s
  writeTimeout: 15s
  idleTimeout: 0s     # 0 for SSE support
  shutdownTimeout: 30s
  requestTimeout: 60s
  sseTimeout: 24h     # Long timeout for SSE connections
  
  # Rate limiting
  rateLimit: 10       # requests per second
  rateLimitBurst: 20
  
  # Request limits
  maxRequestSize: 1048576    # 1MB
  maxSSEConnections: 1000
  
  # Monitoring
  logLevel: info
  logFormat: text
  enableMetrics: false

# Roles configuration is inherited from server.yaml