# Development configuration - overrides for local development
server:
  # Development typically runs on localhost
  host: localhost
  port: "8080"
  
  # More verbose logging for development
  logLevel: debug
  logFormat: text
  
  # Relaxed rate limiting for development
  rateLimit: 100
  rateLimitBurst: 200
  
  # Shorter timeouts for faster feedback during development
  shutdownTimeout: 5s
  
  # Enable metrics for development monitoring
  enableMetrics: false  # Set to true if you want local metrics
  metricsPort: "9090"