# Production configuration - overrides for production deployment
server:
  # Production settings (these would typically be overridden by env vars)
  host: "0.0.0.0"
  port: "8080"
  
  # Production logging
  logLevel: info
  logFormat: json  # JSON for structured logging in production
  
  # Stricter rate limiting for production
  rateLimit: 10
  rateLimitBurst: 20
  
  # Production timeouts
  readTimeout: 30s
  writeTimeout: 30s
  shutdownTimeout: 60s
  
  # Request limits
  maxRequestSize: 5242880    # 5MB for production
  maxSSEConnections: 5000     # Higher limit for production
  
  # Enable metrics in production
  enableMetrics: true
  metricsPort: "9090"