# Development configuration - complete config for local development
server:
  # Basic settings
  maxPlayersPerRoom: 20
  minPlayersPerRoom: 1
  defaultGameSize: 5
  roomCodeLength: 5
  roomTimeout: 24h
  
  # Development server settings
  host: localhost
  port: "8080"
  
  # Timeouts - relaxed for development
  readTimeout: 15s
  writeTimeout: 15s
  idleTimeout: 0s     # 0 for SSE support
  shutdownTimeout: 5s
  requestTimeout: 60s
  sseTimeout: 24h
  
  # Rate limiting - relaxed for development
  rateLimit: 100
  rateLimitBurst: 200
  
  # Request limits
  maxRequestSize: 1048576    # 1MB
  maxSSEConnections: 1000
  
  # Development logging
  logLevel: debug
  logFormat: text
  enableMetrics: false
  metricsPort: "9090"

# Include all role definitions for development
roles:
  available:
    leader:
      displayName: "Leader"
      category: "Leader"
      minCount: 1
      maxCount: 1
      alwaysRevealed: true
    guardian:
      displayName: "Guardian"
      category: "Guardian"
      minCount: 0
      maxCount: 10
    assassin:
      displayName: "Assassin"
      category: "Assassin"
      minCount: 0
      maxCount: 10
    traitor:
      displayName: "Traitor"
      category: "Traitor"
      minCount: 0
      maxCount: 10
  
  presets:
    standard:
      name: "Standard"
      description: "Balanced gameplay for all player counts"
      distributions:
        1: {leader: 1}
        2: {leader: 1, traitor: 1}
        3: {leader: 1, assassin: 1, traitor: 1}
        4: {leader: 1, assassin: 2, traitor: 1}
        5: {leader: 1, guardian: 1, assassin: 2, traitor: 1}